const actions = {
  ADD_CARD: "ADD_CARD",
  UPDATE_CARD: "UPDATE_CARD",
  REMOVE_CARD: "REMOVE_CARD",
  ADD_LIST: "ADD_LIST",
  UPDATE_LIST: "UPDATE_LIST",
  REMOVE_LIST: "REMOVE_LIST",
  REMOVE_MULTIPLE_CARDS: "REMOVE_MULTIPLE_CARDS",
  CHANGE_CARD_POSITION: "CHANGE_CARD_POSITION",
  CHANGE_LIST_POSITION: "CHANGE_LIST_POSITION",
};
export default actions;
